FROM alpine:3.20.3 as alpine
ARG TARGETPLATFORM
LABEL maintainer "Hector <hector@email.gnx>"

EXPOSE 80 443 2019
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

RUN apk add -U --no-cache ca-certificates curl

COPY artifacts/binaries/$TARGETPLATFORM/caddy /bin/

ENTRYPOINT ["/bin/caddy"]

CMD ["tailnet-proxy"]